customhost = "employee-d.ckpnbp79qgby.us-east-2.rds.amazonaws.com"
customuser = "Gautam"
custompass = "Gautamgagan123"
customdb = "employee-d"
custombucket = "projectemployee"
customregion = "us-east-2"
